### PR TITLE
More test coverage

### PR DESCRIPTION
**Pull request by karlnorling**
Adding some more tests.

Screenshot 2019-09-16 at 21 25 42

### CODE REVIEW

**Comment by cv711** [comment]
Why don't we run all those tests during CI builds?

**Comment by karlnorling** [comment]
@cv711 I had issues with downloading and building capnp in circle ci. One have to build it from source and a special version for node 8. And then install the npm capnp lib.

**Comment by cv711** [comment]
@karlnorling we could run the tests inside the sandbox container we are building no?

**Comment by karlnorling** [comment]
@cv711 this is a lot more work than I thought - and I'm not sure if updating the `baseexec` docker image does changes to the built docker image later. I'm also having issues compiling cap'nproto on the alpine distro - it's missing a fair amount of different things.

```
          echo Installing Capn'Proto for node 8
          apk --no-cache add openssl wget
          apk add build-base
          curl -O https://capnproto.org/capnproto-c++-0.6.1.tar.gz
          tar zxf capnproto-c++-0.6.1.tar.gz
          cd capnproto-c++-0.6.1
          ./configure
          make -j6 check
          sudo make install
```
Right now it's failing on `make -j6 check`

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS "-DCAPNP_INCLUDE_DIR=\"/usr/local/include\"" -O2 -DNDEBUG -MT src/kj/mutex.lo -MD -MP -MF src/kj/.deps/mutex.Tpo -c src/kj/mutex.c++  -fPIC -DPIC -o src/kj/.libs/mutex.o
src/kj/mutex.c++:34:25: fatal error: linux/futex.h: No such file or directory
 #include <linux/futex.h>
```
And I have no idea how to install futex kernel tool on alpine distro.

**Pull request merged**
